{"mutant_code": "class MyClass:\n    def __init__(self, x: int):\n        self.x = x\n    \n    def add10(self):\n        return \\\n            (self.x + 15) - 5\n    \n    def double_me(self):\n        return self.x // 2", "number": 4, "mutations": [{"operator": "AOR", "lineno": 10}], "module": "my_class", "status": "killed", "time": 0.0, "killer": "test_double (my_class_test.MyClassTest)", "tests_run": 2, "exception_traceback": "Traceback (most recent call last):\n  File \".\\my_class_test.py\", line 7, in test_double\n    self.assertEqual(c1.double_me(), 4)\nAssertionError: 1 != 4\n"}